
import api from './api';

export const fetchSettings = async (branchId = 1) => {
  try {
    const response = await api.get(`/Settings?branch=${branchId}`);
    const d = response.data?.data || response.data || {};

    return {
      success: true,
      data: {
        ID: d.ID ?? 0,
        SaleWithTax: d.SaleWithTax ?? false,
        BuyWithTax: d.BuyWithTax ?? false,
        Tax_GroupID: d.Tax_GroupID ?? null,
        ISInvoiceDeteil: d.ISInvoiceDeteil ?? false,
        showBranchOnlay: d.showBranchOnlay ?? false,
        DisplayReportBranch: d.DisplayReportBranch ?? false,
        Allow_addInvoiceAut: d.Allow_addInvoiceAut ?? false,
        branch: d.branch ?? branchId,
        userID: d.userID ?? null,
        TheUserID: d.TheUserID ?? null,
        searchIn_SameFormSale: d.searchIn_SameFormSale ?? false,
        ShowMsgAftersaveCashier: d.ShowMsgAftersaveCashier ?? false,
        HideTaxInSale: d.HideTaxInSale ?? false,
        HideTaxInBuy: d.HideTaxInBuy ?? false,
        UsePatientInServiceInvoice: d.UsePatientInServiceInvoice ?? false,
        SimpleSalePrint: d.SimpleSalePrint ?? false,
        SimpleBuyPrint: d.SimpleBuyPrint ?? false,
        SimpleReSalePrint: d.SimpleReSalePrint ?? false,
        SimpleReBuyPrint: d.SimpleReBuyPrint ?? false,
        SimpleServiceSalePrint: d.SimpleServiceSalePrint ?? false,
        SimpleServiceReSalePrint: d.SimpleServiceReSalePrint ?? false,
        SimpleCashierSalePrint: d.SimpleCashierSalePrint ?? false,
        SimpleCashierReSalePrint: d.SimpleCashierReSalePrint ?? false,
        BarcodePrintDirect: d.BarcodePrintDirect ?? false,
        BarcodeType: d.BarcodeType ?? 'Code128',
        BarcodeW: d.BarcodeW ?? 0,
        BarcodeH: d.BarcodeH ?? 0,
        ShowTaf: d.ShowTaf ?? false,
        QRis_big: d.QRis_big ?? false,
        salePrintDirect: d.salePrintDirect ?? false,
        searchForBarcode_sale: d.searchForBarcode_sale ?? false,
        SaleYemen: d.SaleYemen ?? false,
        LinkZakat: d.LinkZakat ?? false,
        SimpleSaleMainCashier: d.SimpleSaleMainCashier ?? false,
        SimpleBuyPrintCashier: d.SimpleBuyPrintCashier ?? false,
        SimpleServiceSaleCashierPrint: d.SimpleServiceSaleCashierPrint ?? false,
        SimpleCashierSale_cashierPrint: d.SimpleCashierSale_cashierPrint ?? false,
        SimpleMadinPoems: d.SimpleMadinPoems ?? false,
        SimpleOfferSale: d.SimpleOfferSale ?? false,
        SimpleResaleCashier: d.SimpleResaleCashier ?? false,
        SimpleRebuyCashier: d.SimpleRebuyCashier ?? false,
        SimpleServiceReSaleCashier: d.SimpleServiceReSaleCashier ?? false,
        SimpleCashierReSaleCashier: d.SimpleCashierReSaleCashier ?? false,
        ShowTaftxt: d.ShowTaftxt ?? false,
        HidPaidForm: d.HidPaidForm ?? false,
        DirectPrintMainSale: d.DirectPrintMainSale ?? false,
        DirectPrintServiceSale: d.DirectPrintServiceSale ?? false,
        DefSafe: d.DefSafe ?? null,
        DefStore: d.DefStore ?? null,
        DefUbit: d.DefUbit ?? null,
        HideBuyPriceFSer: d.HideBuyPriceFSer ?? false,
        AllowSaleMinusSalemain: d.AllowSaleMinusSalemain ?? false,
        AllowSaleMinusSale: d.AllowSaleMinusSale ?? false,
        RefrshSaleItemInSaleMain: d.RefrshSaleItemInSaleMain ?? false,
        RefrshBuyItemInBuy: d.RefrshBuyItemInBuy ?? false,
        PreventSaleIflessThanPricesale: d.PreventSaleIflessThanPricesale ?? false,
        AutoUpdateMiniUnitPriceFromBuys: d.AutoUpdateMiniUnitPriceFromBuys ?? false,
        SearchBarcodeInSaleMain: d.SearchBarcodeInSaleMain ?? false,
        ShowExpaireDate: d.ShowExpaireDate ?? false,
        ShowResturantSys: d.ShowResturantSys ?? false,
        WayShowExpireDate: d.WayShowExpireDate ?? null,
        AllowChangeDate: d.AllowChangeDate ?? false,
        UseReferenceNumber: d.UseReferenceNumber ?? false,
        EnabaledLinkedSafe: d.EnabaledLinkedSafe ?? false,
        PrinterA4Name: d.PrinterA4Name ?? '',
        Printer80CName: d.Printer80CName ?? '',
        PrinterBarcodeName: d.PrinterBarcodeName ?? '',
        ShowSaveMsgToZac: d.ShowSaveMsgToZac ?? false,
        PeriodOFBackUp: d.PeriodOFBackUp ?? 0,
        ActivateOuterBackUp: d.ActivateOuterBackUp ?? false,
        DefGroup: d.DefGroup ?? null,
        UpdateDateBuyInBuys: d.UpdateDateBuyInBuys ?? false,
        LenghtOFPriceField: d.LenghtOFPriceField ?? 10,
        LenghtOfQtyField: d.LenghtOfQtyField ?? 6,
        DirectPrintBuy: d.DirectPrintBuy ?? false,
        ItemShow: d.ItemShow ?? false,
        BtnCatWidth: d.BtnCatWidth ?? 0,
        BtnCatHeight: d.BtnCatHeight ?? 0,
        BtnItemWidth: d.BtnItemWidth ?? 0,
        BtnItemHeight: d.BtnItemHeight ?? 0,
        RcloneName: d.RcloneName ?? '',
        ActiveprinterForKitchen: d.ActiveprinterForKitchen ?? false,
        KichenPrinter: d.KichenPrinter ?? '',
        HidePercentInCashier: d.HidePercentInCashier ?? false,
        AlertEndDateItem: d.AlertEndDateItem ?? false,
        AlertOutSaleItem: d.AlertOutSaleItem ?? false,
        ResTaxPercent: d.ResTaxPercent ?? 0,
        ShowItemButList: d.ShowItemButList ?? false,
        ActiveRestrctionCashNetwork: d.ActiveRestrctionCashNetwork ?? false,
        StopKichenPrint: d.StopKichenPrint ?? false,
        PrintFatoraWithLogo: d.PrintFatoraWithLogo ?? false,
        InvestorPer: d.InvestorPer ?? 0,
        PinsAllBRInItems: d.PinsAllBRInItems ?? false,
        RefrshPrinterRemoteDeskTop: d.RefrshPrinterRemoteDeskTop ?? false,
        StopbkWnCloseForm: d.StopbkWnCloseForm ?? false,
        ShowBrItemOnly: d.ShowBrItemOnly ?? false,
        Def_RES_Catogre: d.Def_RES_Catogre ?? null,
        JoinPrinterbydevice: d.JoinPrinterbydevice ?? false,
      },
    };
  } catch (error) {
    return {
      success: false,
      message: error.response?.data?.message || 'حدث خطأ أثناء جلب الإعدادات',
      data: null,
    };
  }
};

export const updateSettings = async (settingsData) => {
  try {
    const payload = {
      SaleWithTax: settingsData.SaleWithTax ?? false,
      BuyWithTax: settingsData.BuyWithTax ?? false,
      Tax_GroupID: settingsData.Tax_GroupID ?? null,
      ISInvoiceDeteil: settingsData.ISInvoiceDeteil ?? false,
      showBranchOnlay: settingsData.showBranchOnlay ?? false,
      DisplayReportBranch: settingsData.DisplayReportBranch ?? false,
      Allow_addInvoiceAut: settingsData.Allow_addInvoiceAut ?? false,
      branch: settingsData.branch ?? 1,
      userID: settingsData.userID ?? null,
      TheUserID: settingsData.TheUserID ?? null,
      searchIn_SameFormSale: settingsData.searchIn_SameFormSale ?? false,
      ShowMsgAftersaveCashier: settingsData.ShowMsgAftersaveCashier ?? false,
      HideTaxInSale: settingsData.HideTaxInSale ?? false,
      HideTaxInBuy: settingsData.HideTaxInBuy ?? false,
      UsePatientInServiceInvoice: settingsData.UsePatientInServiceInvoice ?? false,
      SimpleSalePrint: settingsData.SimpleSalePrint ?? false,
      SimpleBuyPrint: settingsData.SimpleBuyPrint ?? false,
      SimpleReSalePrint: settingsData.SimpleReSalePrint ?? false,
      SimpleReBuyPrint: settingsData.SimpleReBuyPrint ?? false,
      SimpleServiceSalePrint: settingsData.SimpleServiceSalePrint ?? false,
      SimpleServiceReSalePrint: settingsData.SimpleServiceReSalePrint ?? false,
      SimpleCashierSalePrint: settingsData.SimpleCashierSalePrint ?? false,
      SimpleCashierReSalePrint: settingsData.SimpleCashierReSalePrint ?? false,
      BarcodePrintDirect: settingsData.BarcodePrintDirect ?? false,
      BarcodeType: settingsData.BarcodeType ?? 'Code128',
      BarcodeW: settingsData.BarcodeW ?? 0,
      BarcodeH: settingsData.BarcodeH ?? 0,
      ShowTaf: settingsData.ShowTaf ?? false,
      QRis_big: settingsData.QRis_big ?? false,
      salePrintDirect: settingsData.salePrintDirect ?? false,
      searchForBarcode_sale: settingsData.searchForBarcode_sale ?? false,
      SaleYemen: settingsData.SaleYemen ?? false,
      LinkZakat: settingsData.LinkZakat ?? false,
      SimpleSaleMainCashier: settingsData.SimpleSaleMainCashier ?? false,
      SimpleBuyPrintCashier: settingsData.SimpleBuyPrintCashier ?? false,
      SimpleServiceSaleCashierPrint: settingsData.SimpleServiceSaleCashierPrint ?? false,
      SimpleCashierSale_cashierPrint: settingsData.SimpleCashierSale_cashierPrint ?? false,
      SimpleMadinPoems: settingsData.SimpleMadinPoems ?? false,
      SimpleOfferSale: settingsData.SimpleOfferSale ?? false,
      SimpleResaleCashier: settingsData.SimpleResaleCashier ?? false,
      SimpleRebuyCashier: settingsData.SimpleRebuyCashier ?? false,
      SimpleServiceReSaleCashier: settingsData.SimpleServiceReSaleCashier ?? false,
      SimpleCashierReSaleCashier: settingsData.SimpleCashierReSaleCashier ?? false,
      ShowTaftxt: settingsData.ShowTaftxt ?? false,
      HidPaidForm: settingsData.HidPaidForm ?? false,
      DirectPrintMainSale: settingsData.DirectPrintMainSale ?? false,
      DirectPrintServiceSale: settingsData.DirectPrintServiceSale ?? false,
      DefSafe: settingsData.DefSafe ?? null,
      DefStore: settingsData.DefStore ?? null,
      DefUbit: settingsData.DefUbit ?? null,
      HideBuyPriceFSer: settingsData.HideBuyPriceFSer ?? false,
      AllowSaleMinusSalemain: settingsData.AllowSaleMinusSalemain ?? false,
      AllowSaleMinusSale: settingsData.AllowSaleMinusSale ?? false,
      RefrshSaleItemInSaleMain: settingsData.RefrshSaleItemInSaleMain ?? false,
      RefrshBuyItemInBuy: settingsData.RefrshBuyItemInBuy ?? false,
      PreventSaleIflessThanPricesale: settingsData.PreventSaleIflessThanPricesale ?? false,
      AutoUpdateMiniUnitPriceFromBuys: settingsData.AutoUpdateMiniUnitPriceFromBuys ?? false,
      SearchBarcodeInSaleMain: settingsData.SearchBarcodeInSaleMain ?? false,
      ShowExpaireDate: settingsData.ShowExpaireDate ?? false,
      ShowResturantSys: settingsData.ShowResturantSys ?? false,
      WayShowExpireDate: settingsData.WayShowExpireDate ?? null,
      AllowChangeDate: settingsData.AllowChangeDate ?? false,
      UseReferenceNumber: settingsData.UseReferenceNumber ?? false,
      EnabaledLinkedSafe: settingsData.EnabaledLinkedSafe ?? false,
      PrinterA4Name: settingsData.PrinterA4Name ?? '',
      Printer80CName: settingsData.Printer80CName ?? '',
      PrinterBarcodeName: settingsData.PrinterBarcodeName ?? '',
      ShowSaveMsgToZac: settingsData.ShowSaveMsgToZac ?? false,
      PeriodOFBackUp: settingsData.PeriodOFBackUp ?? 0,
      ActivateOuterBackUp: settingsData.ActivateOuterBackUp ?? false,
      DefGroup: settingsData.DefGroup ?? null,
      UpdateDateBuyInBuys: settingsData.UpdateDateBuyInBuys ?? false,
      LenghtOFPriceField: settingsData.LenghtOFPriceField ?? 10,
      LenghtOfQtyField: settingsData.LenghtOfQtyField ?? 6,
      DirectPrintBuy: settingsData.DirectPrintBuy ?? false,
      ItemShow: settingsData.ItemShow ?? false,
      BtnCatWidth: settingsData.BtnCatWidth ?? 0,
      BtnCatHeight: settingsData.BtnCatHeight ?? 0,
      BtnItemWidth: settingsData.BtnItemWidth ?? 0,
      BtnItemHeight: settingsData.BtnItemHeight ?? 0,
      RcloneName: settingsData.RcloneName ?? '',
      ActiveprinterForKitchen: settingsData.ActiveprinterForKitchen ?? false,
      KichenPrinter: settingsData.KichenPrinter ?? '',
      HidePercentInCashier: settingsData.HidePercentInCashier ?? false,
      AlertEndDateItem: settingsData.AlertEndDateItem ?? false,
      AlertOutSaleItem: settingsData.AlertOutSaleItem ?? false,
      ResTaxPercent: settingsData.ResTaxPercent ?? 0,
      ShowItemButList: settingsData.ShowItemButList ?? false,
      ActiveRestrctionCashNetwork: settingsData.ActiveRestrctionCashNetwork ?? false,
      StopKichenPrint: settingsData.StopKichenPrint ?? false,
      PrintFatoraWithLogo: settingsData.PrintFatoraWithLogo ?? false,
      InvestorPer: settingsData.InvestorPer ?? 0,
      PinsAllBRInItems: settingsData.PinsAllBRInItems ?? false,
      RefrshPrinterRemoteDeskTop: settingsData.RefrshPrinterRemoteDeskTop ?? false,
      StopbkWnCloseForm: settingsData.StopbkWnCloseForm ?? false,
      ShowBrItemOnly: settingsData.ShowBrItemOnly ?? false,
      Def_RES_Catogre: settingsData.Def_RES_Catogre ?? null,
      JoinPrinterbydevice: settingsData.JoinPrinterbydevice ?? false,
    };

    const response = await api.put(`/Settings`, payload);
    return {
      success: true,
      message: response.data?.message || 'تم حفظ الإعدادات بنجاح',
      data: response.data?.data || null,
    };
  } catch (error) {
    return {
      success: false,
      message: error.response?.data?.message || 'حدث خطأ أثناء حفظ الإعدادات',
      data: null,
    };
  }
};